---
title: "Caitlin Clark Analysis"
output: html_document
date: "2024-04-23"
---

```{r setup, include=FALSE}
# install packages 
#install.packages("wehoop") 
#install.packages("ggplot2")
#library(ggplot2)
#install.packages("tidyverse")
#library(tidyverse)
#install.packages("nbastatR")
#library(nbastatR)
#install.packages("devtools")
#library(devtools)
#devtools::install_github("lbenz730/ncaahoopR")
#library(ncaahoopR)
#install.packages("extrafont")
#library(extrafont)
#install.packages("cowplot")
#library(cowplot)
#install.packages("paletteer")
#library(paletteer)
#install.packages("dplyr")
#library(dplyr)
```

```{r}

# Creating court and plotting using the tutorial from https://www.youtube.com/watch?v=Af7g95-g4y8&list=PL10a1_q15Hwr4H5dCXQD3htK5VGfwjrgq&index=2

circle_points = function(center = c(0, 0), radius = 1, npoints = 360) {
  angles = seq(0, 2 * pi, length.out = npoints)
  return(data_frame(x = center[1] + radius * cos(angles),
                    y = center[2] + radius * sin(angles)))
}

# Court Dimenons & lines
width = 50
height = 94 / 2
key_height = 19
inner_key_width = 12
outer_key_width = 16
backboard_width = 6
backboard_offset = 4
neck_length = 0.5
hoop_radius = 0.75
hoop_center_y = backboard_offset + neck_length + hoop_radius
three_point_radius = 23.75
three_point_side_radius = 22
three_point_side_height = 14

# Court themes
court_themes = list(
  light = list(
    court = 'floralwhite',
    lines = '#999999',
    text = '#222222',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 1,
    hex_border_color = "#000000"
  ),
  dark = list(
    court = '#000004',
    lines = '#999999',
    text = '#f0f0f0',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 0,
    hex_border_color = "#000000"
  ),
  ppt = list(
    court = 'gray20',
    lines = 'white',
    text = '#f0f0f0',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 0,
    hex_border_color = "gray20"
)
)

# Function to create court based on given dimensions
plot_court = function(court_theme = court_themes$light, use_short_three = FALSE) {
  if (use_short_three) {
    three_point_radius = 22
    three_point_side_height = 0
  }
  
  court_points = data_frame(
    x = c(width / 2, width / 2, -width / 2, -width / 2, width / 2),
    y = c(height, 0, 0, height, height),
    desc = "perimeter"
  )
  
  court_points = bind_rows(court_points , data_frame(
    x = c(outer_key_width / 2, outer_key_width / 2, -outer_key_width / 2, -outer_key_width / 2),
    y = c(0, key_height, key_height, 0),
    desc = "outer_key"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c(-backboard_width / 2, backboard_width / 2),
    y = c(backboard_offset, backboard_offset),
    desc = "backboard"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c(0, 0), y = c(backboard_offset, backboard_offset + neck_length), desc = "neck"
  ))
  
  foul_circle = circle_points(center = c(0, key_height), radius = inner_key_width / 2)
  
  foul_circle_top = filter(foul_circle, y > key_height) %>%
    mutate(desc = "foul_circle_top")
  
  foul_circle_bottom = filter(foul_circle, y < key_height) %>%
    mutate(
      angle = atan((y - key_height) / x) * 180 / pi,
      angle_group = floor((angle - 5.625) / 11.25),
      desc = paste0("foul_circle_bottom_", angle_group)
    ) %>%
    filter(angle_group %% 2 == 0) %>%
    select(x, y, desc)
  
  hoop = circle_points(center = c(0, hoop_center_y), radius = hoop_radius) %>%
    mutate(desc = "hoop")
  
  restricted = circle_points(center = c(0, hoop_center_y), radius = 4) %>%
    filter(y >= hoop_center_y) %>%
    mutate(desc = "restricted")
  
  three_point_circle = circle_points(center = c(0, hoop_center_y), radius = three_point_radius) %>%
    filter(y >= three_point_side_height, y >= hoop_center_y)
  
  three_point_line = data_frame(
    x = c(three_point_side_radius, three_point_side_radius, three_point_circle$x, -three_point_side_radius, -three_point_side_radius),
    y = c(0, three_point_side_height, three_point_circle$y, three_point_side_height, 0),
    desc = "three_point_line"
  )
  
  court_points = bind_rows(
    court_points,
    foul_circle_top,
    foul_circle_bottom,
    hoop,
    restricted,
    three_point_line
  )
  
  
  court_points <- court_points
  
  # Final plot creation
  ggplot() +
    geom_path(
      data = court_points,
      aes(x = x, y = y, group = desc),
      color = court_theme$lines
    ) +
    coord_fixed(ylim = c(0, 45), xlim = c(-25, 25)) +
    theme_minimal(base_size = 22) +
    theme(
      text = element_text(color = court_theme$text),
      plot.background = element_rect(fill = 'gray20', color = 'gray20'),
      panel.background = element_rect(fill = court_theme$court, color = court_theme$court),
      panel.grid = element_blank(),
      panel.border = element_blank(),
      axis.text = element_blank(),
      axis.title = element_blank(),
      axis.ticks = element_blank(),
      legend.background = element_rect(fill = court_theme$court, color = court_theme$court),
      legend.margin = margin(-1, 0, 0, 0, unit = "lines"),
      legend.position = "bottom",
      legend.key = element_blank(),
      legend.text = element_text(size = rel(1.0))
    )
}


```

```{r}
#loading the data
#wbb_pbp <- wehoop::load_wbb_pbp()
head(wbb_pbp)
summary(wbb_pbp)
str(wbb_pbp)

```



# Caitlin Clark Shooting Analysis 
```{r}
# Filtering the data for Caitlin Clark Shooting  
clark_shooting_data <- wbb_pbp %>%
  filter(shooting_play == TRUE,  athlete_id_1 == 4433403) %>%
  filter(!grepl("FreeThrow", type_text))


# Mutate to flip the x_coordinate values conditionally
clark_shooting_data <- clark_shooting_data %>%
  mutate(coordinate_x = ifelse(coordinate_x > 0, -coordinate_x, coordinate_x))


# Displaying the filtered data
clark_shooting_data <- clark_shooting_data %>% mutate(coordinate_x = coordinate_x + 47)

# Convert 'scoring_play' from logical to factor
clark_shooting_data$scoring_play <- factor(clark_shooting_data$scoring_play, 
                                           levels = c(FALSE, TRUE), 
                                           labels = c("Missed", "Made"))

print(clark_shooting_data)


# Filtering the data for Clark shots without assists 
clark_shooting_noassist_data <- clark_shooting_data %>%
  filter(scoring_play == "Made")  %>%
  filter(!grepl("Assisted by", text)) %>%
  filter(!grepl("FreeThrow", type_text))

# Filtering data for Clark vs Michigan 02/15/2024
clark_michigan_data <- clark_shooting_data %>%
  filter( game_date == "2024-02-15")
clark_michigan_data


# Filtering data for Clark vs Indiana 02/22/2024
clark_indiana_data <- clark_shooting_data %>%
  filter( game_date == "2024-02-22")
clark_indiana_data


```

```{r}
# Plot Clark's shooting chart 
p1 <- plot_court(court_themes$ppt, use_short_three = T) +
  geom_point(data = clark_shooting_data, aes(x = coordinate_y, y = coordinate_x, color = scoring_play, fill = scoring_play), size =2.5, shape = 21, stroke = .5) +  
  scale_color_manual(values = c("Made" = "green4", "Missed" = "red3")) +
  scale_fill_manual(values = c("Made" = "green2", "Missed" = "gray20")) +
  scale_x_continuous(limits = c(-27.5, 27.5)) + 
  scale_y_continuous(limits = c(0, 47)) +
  theme(plot.title = element_text(hjust = .5, size = 22, family = "Comic Sans MS", face = "bold", vjust = -4),
        plot.subtitle = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", vjust = -8),
        legend.position = c(.5, .85),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.text = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", colour = "white"),
        plot.caption = element_text(hjust = .5, size = 6, family = "Comic Sans MS", face = "bold", colour = "lightgrey", vjust = 8)) +
  ggtitle(label = "Caitlin Clark",
          subtitle = "Shots Chart 2023-24 Season") 


ggdraw(p1) + theme(plot.background = element_rect(fill="gray20", color = NA)) 

# save the image as png
ggsave("Clark_shooting_chart.png", height = 6, width = 6, dpi = 300)

# Heat Map 
palette <- paletteer::paletteer_d("RColorBrewer::YlOrRd", direction = -1)

p1 <- plot_court(court_themes$ppt, use_short_three = T) + 
  geom_density_2d_filled(clark_shooting_data, mapping = aes(x = coordinate_y, y = coordinate_x,fill = ..level..,),
                         contour_var = "ndensity", breaks = seq(0.1, 1.0, length.out = 10), alpha = .5)  + 
  scale_fill_manual(values = c(palette), aesthetics = c("fill", "color")) +
  scale_x_continuous(limits = c(-27.5, 27.5)) + 
  scale_y_continuous(limits = c(0, 47)) +
  theme(legend.position = "none",
        plot.title = element_text(hjust = .5, size = 22, family = "Comic Sans MS", face = "bold", vjust = -4),
        plot.subtitle = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", vjust = -8),
        legend.title = element_blank(),
        legend.text = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", colour = "white"),
        plot.caption = element_text(hjust = .5, size = 6, family = "Comic Sans MS", face = "bold", colour = "lightgrey", vjust = 8)) +
  labs(title = "Caitlin Clark",
          subtitle = "Shooting Heat Map Without Assists") 

ggdraw(p1) + theme(plot.background = element_rect(fill="gray15", color = NA)) 

ggsave("Clark_heat_woassist.png", height = 6, width = 6, dpi = 300)
```

```{r}
# Plot Clark's shooting chart without assist 
p1 <- plot_court(court_themes$ppt, use_short_three = T) +
  geom_point(data = clark_shooting_noassist_data, aes(x = coordinate_y, y = coordinate_x, color = scoring_play, fill = scoring_play), size =2.5, shape = 21, stroke = .5) +  
  scale_color_manual(values = c("green4","red3"), aesthetics = "color", labels=c("Made", "Missed")) +
  scale_fill_manual(values = c("green2","gray20"), aesthetics = "fill", labels=c("Made", "Missed")) +
  scale_x_continuous(limits = c(-27.5, 27.5)) + 
  scale_y_continuous(limits = c(0, 47)) +
  theme(plot.title = element_text(hjust = .5, size = 22, family = "Comic Sans MS", face = "bold", vjust = -4),
        plot.subtitle = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", vjust = -8),
        legend.position = c(.5, .85),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.text = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", colour = "white"),
        plot.caption = element_text(hjust = .5, size = 6, family = "Comic Sans MS", face = "bold", colour = "lightgrey", vjust = 8)) +
  ggtitle(label = "Caitlin Clark",
          subtitle = "Shoting Chart Without Assists 2023-24 Season") 


ggdraw(p1) + theme(plot.background = element_rect(fill="gray20", color = NA)) 

# Heat Map 
palette <- paletteer::paletteer_d("RColorBrewer::YlOrRd", direction = -1)

p1 <- plot_court(court_themes$ppt, use_short_three = T) + 
  geom_density_2d_filled(clark_shooting_noassist_data, mapping = aes(x = coordinate_y, y = coordinate_x,fill = ..level..,),
                         contour_var = "ndensity", breaks = seq(0.1, 1.0, length.out = 10), alpha = .5)  + 
  scale_fill_manual(values = c(palette), aesthetics = c("fill", "color")) +
  scale_x_continuous(limits = c(-27.5, 27.5)) + 
  scale_y_continuous(limits = c(0, 47)) +
  theme(legend.position = "none",
        plot.title = element_text(hjust = .5, size = 22, family = "Comic Sans MS", face = "bold", vjust = -4),
        plot.subtitle = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", vjust = -8),
        legend.title = element_blank(),
        legend.text = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", colour = "white"),
        plot.caption = element_text(hjust = .5, size = 6, family = "Comic Sans MS", face = "bold", colour = "lightgrey", vjust = 8)) +
  labs(title = "Caitlin Clark",
          subtitle = "Shooting Heat Map Without Assists") 

ggdraw(p1) + theme(plot.background = element_rect(fill="gray15", color = NA)) 

ggsave("Clark_heat_woassist.png", height = 6, width = 6, dpi = 300)
```

# Clark shooting vs Michigan & Indiana 

```{r}
# VS Michigan
p1 <- plot_court(court_themes$ppt, use_short_three = T) +
  geom_point(data = clark_michigan_data, aes(x = coordinate_y, y = coordinate_x, color = scoring_play, fill = scoring_play), size =2.5, shape = 21, stroke = .5) +  
  scale_color_manual(values = c("Made" = "green4", "Missed" = "red3")) +
  scale_fill_manual(values = c("Made" = "green2", "Missed" = "gray20")) +
scale_x_continuous(limits = c(-27.5, 27.5)) + 
  scale_y_continuous(limits = c(0, 47)) +
  theme(plot.title = element_text(hjust = .5, size = 22, family = "Comic Sans MS", face = "bold", vjust = -4),
        plot.subtitle = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", vjust = -8),
        legend.position = c(.5, .85),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.text = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", colour = "white"),
        plot.caption = element_text(hjust = .5, size = 6, family = "Comic Sans MS", face = "bold", colour = "lightgrey", vjust = 8)) +
  ggtitle(label = "Caitlin Clark",
          subtitle = "Shooting Chart vs Michigan 2024-02-15") 


ggdraw(p1) + theme(plot.background = element_rect(fill="gray20", color = NA)) 


# Heat Map vs Michigan
palette <- paletteer::paletteer_d("RColorBrewer::YlOrRd", direction = -1)

p1 <- plot_court(court_themes$ppt, use_short_three = T) + 
  geom_density_2d_filled(clark_michigan_data, mapping = aes(x = coordinate_y, y = coordinate_x,fill = ..level..,),
                         contour_var = "ndensity", breaks = seq(0.1, 1.0, length.out = 10), alpha = .5)  + 
  scale_fill_manual(values = c(palette), aesthetics = c("fill", "color")) +
  scale_x_continuous(limits = c(-27.5, 27.5)) + 
  scale_y_continuous(limits = c(0, 47)) +
  theme(legend.position = "none",
        plot.title = element_text(hjust = .5, size = 22, family = "Comic Sans MS", face = "bold", vjust = -4),
        plot.subtitle = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", vjust = -8),
        legend.title = element_blank(),
        legend.text = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", colour = "white"),
        plot.caption = element_text(hjust = .5, size = 6, family = "Comic Sans MS", face = "bold", colour = "lightgrey", vjust = 8)) +
  labs(title = "Caitlin Clark",
          subtitle = "Shooting Heat Map vs Michigan") 

ggdraw(p1) + theme(plot.background = element_rect(fill="gray15", color = NA)) 
ggsave("Clark_heatmap_michigan.png", height = 6, width = 6, dpi = 300)


# VS Indiana
p1 <- plot_court(court_themes$ppt, use_short_three = T) +
  geom_point(data = clark_indiana_data, aes(x = coordinate_y, y = coordinate_x, color = scoring_play, fill = scoring_play), size =2.5, shape = 21, stroke = .5) +  
  scale_color_manual(values = c("Made" = "green4", "Missed" = "red3")) +
  scale_fill_manual(values = c("Made" = "green2", "Missed" = "gray20")) +
scale_x_continuous(limits = c(-27.5, 27.5)) + 
  scale_y_continuous(limits = c(0, 47)) +
  theme(plot.title = element_text(hjust = .5, size = 22, family = "Comic Sans MS", face = "bold", vjust = -4),
        plot.subtitle = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", vjust = -8),
        legend.position = c(.5, .85),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.text = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", colour = "white"),
        plot.caption = element_text(hjust = .5, size = 6, family = "Comic Sans MS", face = "bold", colour = "lightgrey", vjust = 8)) +
  ggtitle(label = "Caitlin Clark",
          subtitle = "Shooting Chart vs Indiana ") 


ggdraw(p1) + theme(plot.background = element_rect(fill="gray20", color = NA)) 
ggsave("Clark_shooting_Indiana.png", height = 6, width = 6, dpi = 300)

# Heat Map vs Indiana
palette <- paletteer::paletteer_d("RColorBrewer::YlOrRd", direction = -1)

p1 <- plot_court(court_themes$ppt, use_short_three = T) + 
  geom_density_2d_filled(clark_indiana_data, mapping = aes(x = coordinate_y, y = coordinate_x,fill = ..level..,),
                         contour_var = "ndensity", breaks = seq(0.1, 1.0, length.out = 10), alpha = .5)  + 
  scale_fill_manual(values = c(palette), aesthetics = c("fill", "color")) +
  scale_x_continuous(limits = c(-27.5, 27.5)) + 
  scale_y_continuous(limits = c(0, 47)) +
  theme(legend.position = "none",
        plot.title = element_text(hjust = .5, size = 22, family = "Comic Sans MS", face = "bold", vjust = -4),
        plot.subtitle = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", vjust = -8),
        legend.title = element_blank(),
        legend.text = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", colour = "white"),
        plot.caption = element_text(hjust = .5, size = 6, family = "Comic Sans MS", face = "bold", colour = "lightgrey", vjust = 8)) +
  labs(title = "Caitlin Clark",
          subtitle = "Shooting Heat Map vs Indiana") 

ggdraw(p1) + theme(plot.background = element_rect(fill="gray15", color = NA)) 
#ggsave("Clark_heatmap_Indiana.png", height = 6, width = 6, dpi = 300)


```


# Caitlin Clark Assists 
```{r}
# Filtering the data for Caitlin Clark 
clark_assist_data <- wbb_pbp %>%
  filter(shooting_play == TRUE,  athlete_id_2 == 4433403) %>%
  filter(!grepl("FreeThrow", type_text))


# Mutate to flip the x_coordinate values conditionally
clark_assist_data <- clark_assist_data %>%
  mutate(coordinate_x = ifelse(coordinate_x > 0, -coordinate_x, coordinate_x))


# Displaying the filtered data
clark_assist_data <- clark_assist_data %>% mutate(coordinate_x = coordinate_x+47)
print(clark_assist_data)


# Assume 'data' is your dataframe.
number_of_unique_type <- length(unique(clark_assist_data$athlete_id_1))
number_of_unique_type
```


```{r}
# Plot Clark's assist chart 
p1 <- plot_court(court_themes$ppt, use_short_three = T) +
  geom_point(data = clark_assist_data, aes(x = coordinate_y, y = coordinate_x, color = scoring_play, fill = scoring_play), size =2.5, shape = 21, stroke = .5) +  
  scale_color_manual(values = c("green4","red3"), aesthetics = "color", labels=c("Made", "Missed")) +
  scale_fill_manual(values = c("green2","gray20"), aesthetics = "fill", labels=c("Made", "Missed")) +
  scale_x_continuous(limits = c(-27.5, 27.5)) + 
  scale_y_continuous(limits = c(0, 47)) +
  theme(plot.title = element_text(hjust = .5, size = 22, family = "Comic Sans MS", face = "bold", vjust = -4),
        plot.subtitle = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", vjust = -8),
        legend.position = c(.5, .85),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.text = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", colour = "white"),
        plot.caption = element_text(hjust = .5, size = 6, family = "Comic Sans MS", face = "bold", colour = "lightgrey", vjust = 8)) +
  ggtitle(label = "Caitlin Clark",
          subtitle = "Assists Chart 2023-24 Season") 


ggdraw(p1) + theme(plot.background = element_rect(fill="gray20", color = NA)) 

# save the image as png
ggsave("Clark_assist_chart.png", height = 6, width = 6, dpi = 300)

```

```{r}
# Iowa Shooting analysis 

# Filter play by play data for only Iowa players
Iowa_shooting_data <- wbb_pbp %>%
  filter(shooting_play == TRUE) %>%
  filter(home_team_name == "Iowa" | away_team_name == "Iowa") %>%
  filter(grepl("Kate Martin", text) | grepl("Caitlin Clark", text) | grepl("Molly Davis", text) | grepl("Taylor McCabe", text) | grepl("Sydney Affolter", text) | grepl("Gabbie Marshall", text) | grepl("AJ Ediger", text) | grepl("Hannah Stuelke", text) | grepl("Jada Gyamfi", text) | grepl("Kylie Feuerbach", text) | grepl("Sharon Goodman", text) | grepl("Addison O'Grady", text) | grepl("Kennise Johnson", text) | grepl("Ava Jones", text)) %>%
  filter(!grepl("FreeThrow", type_text))


# Mutate to flip the x_coordinate values conditionally
Iowa_shooting_data <- Iowa_shooting_data %>%
  mutate(coordinate_x = ifelse(coordinate_x > 0, -coordinate_x, coordinate_x))


# Displaying the filtered data
Iowa_shooting_data <- Iowa_shooting_data %>% mutate(coordinate_x = coordinate_x+47)
print(Iowa_shooting_data)

```


# IOWA Team Offense Analysis 
```{r}
# Plot Iowa's shooting chart 
p1 <- plot_court(court_themes$ppt, use_short_three = T) +
  geom_point(data = Iowa_shooting_data, aes(x = coordinate_y, y = coordinate_x, color = scoring_play, fill = scoring_play), size =2.5, shape = 21, stroke = .5) +  
  scale_color_manual(values = c("green4","red3"), aesthetics = "color", labels=c("Made", "Missed")) +
  scale_fill_manual(values = c("green2","gray20"), aesthetics = "fill", labels=c("Made", "Missed")) +
  scale_x_continuous(limits = c(-27.5, 27.5)) + 
  scale_y_continuous(limits = c(0, 47)) +
  theme(plot.title = element_text(hjust = .5, size = 22, family = "Comic Sans MS", face = "bold", vjust = -4),
        plot.subtitle = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", vjust = -8),
        legend.position = c(.5, .85),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.text = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", colour = "white"),
        plot.caption = element_text(hjust = .5, size = 6, family = "Comic Sans MS", face = "bold", colour = "lightgrey", vjust = 8)) +
  ggtitle(label = "Iowa Hawkeyes",
          subtitle = "Shooting Chart 2023-24 Season") 


ggdraw(p1) + theme(plot.background = element_rect(fill="gray20", color = NA)) 

# Plot Iowa's heat map 
palette <- paletteer::paletteer_d("RColorBrewer::YlOrRd", direction = -1)

p1 <- plot_court(court_themes$ppt, use_short_three = T) + 
  geom_density_2d_filled(Iowa_shooting_data, mapping = aes(x = coordinate_y, y = coordinate_x,fill = ..level..,),
                         contour_var = "ndensity", breaks = seq(0.1, 1.0, length.out = 10), alpha = .5)  + 
  scale_fill_manual(values = c(palette), aesthetics = c("fill", "color")) +
  scale_x_continuous(limits = c(-27.5, 27.5)) + 
  scale_y_continuous(limits = c(0, 47)) +
  theme(legend.position = "none",
        plot.title = element_text(hjust = .5, size = 22, family = "Comic Sans MS", face = "bold", vjust = -4),
        plot.subtitle = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", vjust = -8),
        legend.title = element_blank(),
        legend.text = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", colour = "white"),
        plot.caption = element_text(hjust = .5, size = 6, family = "Comic Sans MS", face = "bold", colour = "lightgrey", vjust = 8)) +
  labs(title = "Iowa Hawkeyes Heatmap",
          subtitle = "2023-24 Season") 

ggdraw(p1) + theme(plot.background = element_rect(fill="gray15", color = NA)) 

```

